package com.project.micro_realtime.model;

public enum OrderEventType {
    CREATED, INVENTORY_RESERVED, INVENTORY_RELEASED,
    PAYMENT_PROCESSING, PAYMENT_COMPLETED, PAYMENT_FAILED,
    DRIVER_ASSIGNED, PREPARING, PICKED_UP,
    ON_THE_WAY, DELIVERED, CANCELLED, REFUNDED,
    RATED, FEEDBACK_ADDED
}
