apiVersion: v1
kind: Secret
metadata:
  name: ceiba-secrets
  namespace: ceiba-bar
type: Opaque
data:
  # Base de Datos (Postgres)
  # ceiba_admin / Haikyuu1212
  postgres-user: Y2VpYmFfYWRtaW4=
  postgres-password: SGFpa3l1dTEyMTI=

  # MongoDB
  # ceiba_mongo / Haikyuu1212
  mongo-root-username: Y2VpYmFfbW9uZ28=
  mongo-root-password: SGFpa3l1dTEyMTI=

  # Redis
  # Haikyuu1212
  redis-password: SGFpa3l1dTEyMTI=

  # RabbitMQ
  # ceiba_rabbit / Haikyuu1212
  rabbitmq-username: Y2VpYmFfcmFiYml0
  rabbitmq-password: SGFpa3l1dTEyMTI=

  # Keycloak
  # admin / Haikyuu1212
  keycloak-admin: YWRtaW4=
  keycloak-admin-password: SGFpa3l1dTEyMTI=
  keycloak-db-password: SGFpa3l1dTEyMTI=
  keycloak-client-secret: VlFqQUFqeGNCVU5LcjdKbVhPS2VDVXFRQWtGZGhtdTM=

  # Init Admin
  init-admin-name: Sm9zaHVh
  init-admin-lastname: QWx2YXJleg==
  init-admin-email: Y3Jpc3RvcGhlcjE3QGhvdG1haWwuY29t
  init-admin-password: MTcwNDk4

  # Stripe
  stripe-secret-key: c2tfdGVzdF81MVNjWndGQWJMcFJ0cDFiZTkxUmh5eFJvM01SSmRHRXRpQ1YzSENmTmcxZFpIeTFESTdyeEQxU0ZPcTd3VXI2cEtZTFAzRENLYjlXSE5JV1ltemdwNUpiODAwd0E5bDdta2I=
  stripe-publishable-key: cGtfdGVzdF81MVNjWndGQWJMcFJ0cDFiZWZYaTFLUDJ6M05BaXV4SHZqRDQwbzdnbVFBMUExdnR6R3NQN0I1UnBvSGxsekVtVTNwbXA5QUdpeTZGSmpKWExEbkEycnFIUTAwUW9xSU5FRGg=
  stripe-webhook-secret: d2hzZWNfZTNhMDYyNDdjNjJiNTQwOGI1Yjk0Yzc4YjJlMGM5NmVmNjljM2UxNTEwYWQ5Zjk2ZjlhYTVkMWNhZDUwMzA4Zg==

  # PayPal
  paypal-client-id: QVFpUFptREZIQTBWZWdMZ3NJTGRjSEpUd3ptSndKYzZFcXVFblYweGhjaVptR1FaVnQwRjhKTGhvZzZXLWRTZWx0aG9vQWlQZnpENEplckg=
  paypal-client-secret: RUM3UEthSDgzRllWSGRkZmhwRW1qV1pLeGExS0VBS2lwRGgwemxfNEdydHB1MWZkc0ZoWkw1UnliSmRHYlN4NHgxMjk4eDc4eklzSFd5OFU=

  # MinIO
  # ceiba_minio / Haikyuu1212
  minio-user: Y2VpYmFfbWluaW8=
  minio-password: SGFpa3l1dTEyMTI=

  # JWT Secret
  jwt-secret: N2E4YzNkOGU5ZjBiMWMyZDNlNGY1YTZiN2M4ZDllMGYxYTJiM2M0ZDVlNmY3YThiOWMwZDFlMmYzYTRiNWM2ZA==

  # Internal Inter-service API Key
  internal-api-key: Y2VpYmEtYmFyLWs4cy1pbnRlcm5hbC1rZXktMjAyNi1zZWN1cmU=
