apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: ceiba-bar
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: ceiba-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0
          args: ["start-dev", "--import-realm"]
          env:
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres:5432/keycloak_db"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ceiba-secrets
                  key: postgres-user
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ceiba-secrets
                  key: postgres-password
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: ceiba-secrets
                  key: keycloak-admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ceiba-secrets
                  key: keycloak-admin-password
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: realm-import-vol
              mountPath: /opt/keycloak/data/import
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 200
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 25
          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 240
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 25
      volumes:
        - name: realm-import-vol
          configMap:
            name: keycloak-realm
