# ========== CONFIGURACIÓN DOCKER (Desarrollo en contenedores) ==========
spring.application.name=micro-usuarios
server.port=8089

eureka.instance.instance-id=${spring.application.name}

# Eureka Config
eureka.client.service-url.defaultZone=http://eureka:8762/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=usuarios
ribbon.ConnectTimeout=5000
ribbon.ReadTimeout=30000

# Database Config (Postgres) - Hostname de Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/deliverydb
spring.datasource.username=postgres
spring.datasource.password=Haikyuu1212
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
